### ISSUE TITLE
Integrate Aquisitive Soul Gems Multithreaded

### ISSUE THREAD

**Issue by Infernio** [Infernio/Anofeyn#1]
# Soul Gem Requirements / ASGM

[Acquisitive Soul Gems Multithreaded](www.nexusmods.com/skyrim/mods/65975/?) will be required due to engine / papyrus limitations, but: 
  - Not everyone wants to use an esp slot on it
  - Unless we make it a hard dependency (via masters), users WILL ignore the mod description and simply not install any soul gem mods, breaking Anofeyn
  - Some people already use other soul gem 'fixes' ([Smart Souls](http://www.nexusmods.com/skyrim/mods/14559/?), [Acquisitive Soul Gems](http://www.nexusmods.com/skyrim/mods/5312/?) or [The Soul Saver](http://www.nexusmods.com/skyrim/mods/76899/?))

The solution is to either write our own soul gem 'fix' (that would basically just be a slightly reformatted ASGM anyways) or to merge a modified ASGM into Anofeyn. I chose the latter option.

## Why ASGM?
  - Smart Souls is an SKSE plugin and will therefore not work on SSE
  - ASG is outdated, ASGM is its updated and improved version
  - The Soul Saver does not do the things I need from such a soul gem 'fix' in order for Anofeyn to exist
  - The permissions of ASGM allow building upon / modifying the mod as long as credit is given
  - There is an opportunity to improve and expand upon parts of the mod and integrate it with Anofeyn

## 0.1 TODO:
  - [x] A modified version of ASGM should be merged into Anofeyn.
  - [x] The MCM should be merged into Anofeyn's MCM.
  - [ ] The book should be merged into Anofeyn's book.
  - [x] Improvements to the scripts should be made whenever applicable.
  - [x] The user should receive warnings on startup about incompatible / outdated soul gem mods.
  - [ ] Look into if / how USLEEP fixes the soul trapping process so that it creates soul gems with correct item IDs and merge that fix into Anofeyn if necessary.

## Things Anofeyn currently changes in ASGM
  - Many expensive Debug.Traces have been commented out. Most users have debug logging disabled anyways, so it's easier to just tell them to enable it and install a special debug script in case of bugs - if they're willing to listen to the fist part, they'll probably listen to the second part as well. For the rest of us, it's free performance and lowers the impact each individual soul trap has.
  - The mod's settings can now be changed via console (they are now distinct global variables with intuitive meaning, compared to ASGM's bitfield. Yeah, try explaining that to a user).
  - magicsoultrapfxscript has been significantly improved:
    - No longer calls several Game.GetFormFromFiles every time the script runs, *significantly* improving its performance (it instead uses properties assigned in the CK, checks those against None and only calls GetFormFromFile if the properties aren't set - which indicates a load order conflict or a different mod using the same script).
    - Changed several variables to be local variables instead, reducing the memory impact each individual soul trap has.
    - It will now also check if the vanilla properties have been filled and fill them if they aren't, fixing compatibility with any mods that (stupidly) remove those.

## Technical reasons:
For those who care / want to know (and as a reminder for myself when I inevitably forget it):
  - Anofeyn requires using souls during necromancy. These can be from soul gems or from other methods (in the future). Different soul sizes would give different benefits, buffs, durations etc.
  - In Skyrim, there are two items for every soul gem: an empty soul gem and a fully filled soul gem.
  - When soul trapping, the soul gem's ID does *not* change - it is still considered an 'empty' soul gem, but some hardcoded system inaccessible from Papyrus or the CK stores the information about the size of the soul trapped in it.
  - This means soul trapping in vanilla never actually gives you a different 'filled soul gem' - except in cases where the full soul is trapped in the appropriate soul gem (might be a USLEEP fix? see above).
  - Therefore, the only way to properly check if the player has non-empty soul gems to use is to always force souls to only fill the appropriate soul gems.
  - To do that, we'll have to use one of these soul gem 'fixes' - and that's where ASGM comes in.

## Risks / Alternatives
If the original author wants his mod portion removed, we'll have to write a soul gem mod from scratch - shouldn't be too difficult though.

**Comment by Infernio** [comment]
Removed ASGM, see #3.
