### ISSUE TITLE
Resurrection

### ISSUE THREAD

**Issue by Infernio** [Infernio/Anofeyn#2]
# Resurrection
The most basic form of necromancy, resurrection simply revolves around the, well, resurrection of dead bodies.

## Ideas
  - Resurrecting a corpse requires a soul that will be bound to that corpse.
  - Success chance and the end result depends on several factors - soul size, conjuration skill, level difference, how fresh the corpse is and an MCM / config book setting for difficulty.
  - Overall, this mod will make it *easier* to resurrect things, but makes it more dangerous and the final minion might be weaker or stronger, depending on how 'generous' you're feeling with souls.
  - A more powerful spell will not only make you more likely to succeed, it will also give your minions more powerful buffs.
  - Recently deceased bodies are especially dangerous, because the soul is still closely bound to the body.
  - Dead Thrall will be gone. It's boring and uninteresting. Such an effect should be more difficult to achieve (if it should be at all accessible).

## Lore Basis
As per usual with Elder Scrolls lore, there are many different sources saying different things and they should all be read with the author and their intentions in mind. The only thing every text seems to agree on is that resurrection requires binding a soul to a body.
That said, this mod is mainly taking inspiration from the more recent Online lore from books such as [On Necromancy](http://en.uesp.net/wiki/Lore:On_Necromancy), [On Summoning Skeletons](http://en.uesp.net/wiki/Lore:On_Summoning_Skeletons) and the Morrowind book [Corpse Preparation](http://en.uesp.net/wiki/Lore:Corpse_Preparation).

## 0.1 TODOs
  - [x] Replace all vanilla necromancy spells and scrolls / staffs with resurrection spells.
  - [x] Write the code required to recreate the effects mentioned above.
  - [ ] Implement the buffs to minions.
  - [ ] Make it sure it doesn't block / significantly disadvantage enemy necromancers.
